package br.metodista.poo;

/**
 * @title  POO Aula 08 Exercício 01 - Vetores
 * @since  08.10.2014
 * @author Leandro Melão Medeiros <leandro.medeiros.br@gmail.com> - R.A. 250544
 */
public class MainForm extends javax.swing.JFrame {
    private CaixaDeNumeros lista;
    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.resetArray(false);
    }

    private void resetArray(boolean fixedValues) {
        this.lista = new CaixaDeNumeros(fixedValues);
        
        String values = "";
        
        int idx = 0;
        while (idx < this.lista.values.length) {
            values += (this.lista.values[idx] + ", ");
            idx++;
        }
        
        this.txtResult.setText(values);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMaxValue = new javax.swing.JButton();
        btnMinValue = new javax.swing.JButton();
        btnInvertArray = new javax.swing.JButton();
        btnSumValues = new javax.swing.JButton();
        btnAvgValue = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtResult = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POO A08E01 - Vetores");

        btnMaxValue.setText("Maior Valor");
        btnMaxValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxValueActionPerformed(evt);
            }
        });

        btnMinValue.setText("Menor Valor");
        btnMinValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinValueActionPerformed(evt);
            }
        });

        btnInvertArray.setText("Inverter Vetor");
        btnInvertArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvertArrayActionPerformed(evt);
            }
        });

        btnSumValues.setText("Soma dos Valores");
        btnSumValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumValuesActionPerformed(evt);
            }
        });

        btnAvgValue.setText("Valor Médio");
        btnAvgValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvgValueActionPerformed(evt);
            }
        });

        btnReset.setText("Novos Valores Aleatórios");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultActionPerformed(evt);
            }
        });

        jButton1.setText("Valores Fixos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtResult)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnMinValue, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnInvertArray))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSumValues)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAvgValue, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaxValue)
                    .addComponent(btnMinValue)
                    .addComponent(btnInvertArray))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumValues)
                    .addComponent(btnAvgValue)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInvertArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvertArrayActionPerformed
        this.txtResult.setText(this.lista.getUpsideDownListS());
    }//GEN-LAST:event_btnInvertArrayActionPerformed

    private void btnSumValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumValuesActionPerformed
        this.txtResult.setText(String.valueOf(this.lista.getSum()));
    }//GEN-LAST:event_btnSumValuesActionPerformed

    private void txtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        this.resetArray(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnMaxValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxValueActionPerformed
        this.txtResult.setText(String.valueOf(this.lista.getMaxValue()));
    }//GEN-LAST:event_btnMaxValueActionPerformed

    private void btnMinValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinValueActionPerformed
        this.txtResult.setText(String.valueOf(this.lista.getMinValue()));
    }//GEN-LAST:event_btnMinValueActionPerformed

    private void btnAvgValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvgValueActionPerformed
        this.txtResult.setText(String.valueOf(this.lista.getAverage()));
    }//GEN-LAST:event_btnAvgValueActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.resetArray(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvgValue;
    private javax.swing.JButton btnInvertArray;
    private javax.swing.JButton btnMaxValue;
    private javax.swing.JButton btnMinValue;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSumValues;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
